version: '3.8'

services:
  dwh:
    container_name: dwh
    image: postgres:11-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network

  etl:
    container_name: etl
    build: ./etl
    volumes:
      - ./data:/data
      - ./.env:/.env
    depends_on:
      - dwh
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
